
// This guess the number game is a short TypeScript/Node.js 
// This project that allows the user to guess the number generated by the computer. 
// There are also several ways to alter the game, like adding more rounds or displaying the score. 
// It’s quite simple and uses the random function to generate a number.
// Create a GitHub repository for the project and submit its URL in the project submission form.

//                          NUMBER GUESSING GAME:
#! /usr/bin/env node

import inquirer from "inquirer"

let roundNumber: number = Math.floor((Math.random() * 4) + 1);
let userInput = await inquirer.prompt({
type: "number",
name: "guessedNumber",
message: "Guess a number between 1 - 4"
})
1
if(userInput.guessedNumber === roundNumber) {
    console.log("Congratulation! You guessed correctly!.");
}
else {
    console.log(`Sorry! try next time. The correct No. is: ${roundNumber}`);
}